packages:
  - artifacts/*

autoInstallPeers: false

catalog:
  '@replit/vite-plugin-cartographer': 0.5.21
  '@replit/vite-plugin-dev-banner': 0.1.2
  '@replit/vite-plugin-runtime-error-modal': 0.0.6
  '@tailwindcss/vite': 4.3.3
  '@tanstack/react-query': 5.102.8
  '@types/node': 25.9.5
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.7
  '@vitejs/plugin-react': 5.2.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  framer-motion: 12.43.0
  lucide-react: 0.545.0
  react: 19.1.0
  react-dom: 19.1.0
  tailwind-merge: 3.6.0
  tailwindcss: 4.3.3
  vite: 7.3.6
  wouter: ^3.11.0
  zod: 3.25.76
